/**
 * App-wide shared TypeScript types.
 *
 * Note: database document types are generated by Convex in
 * `convex/_generated/dataModel` (e.g. `Doc<"messages">`, `Id<"messages">`).
 * Prefer those for anything that maps directly to a table. Use this file for
 * UI-only or cross-cutting types that don't live in the database.
 */

export type Theme = "light" | "dark" | "system";
